import {
  // BasketballFoul,
  // CloudVPN,
  DataTransformation,
  // LotteryAlgorithm,
  MobileApp,
  SortingAlgorithmImage,
} from '../assets/images';
import {ProjectItemType} from '../type/ProjectItem';

export const ProjectItems: Array<ProjectItemType> = [
  {
    title: 'Sorting Algorithm Visualizer',
    projectID: 'sorting-visualizer',
    imageList: [
      SortingAlgorithmImage,
      SortingAlgorithmImage,
      SortingAlgorithmImage,
    ],
    ndaSigned: false,
    description: `As a visual learner, this project significantly enhanced my understanding of how sorting algorithms function at a fundamental level. By visualizing the sorting process, I gained insights into the inner workings of algorithms like bubble sort and merge sort. This project reflects my commitment to learning and exploring complex concepts through interactive and visually engaging experiences. \n\n Naturally, I encountered several challenges while working on this project. \nOne major challenge was optimizing the performance of the visualization, especially with large datasets, to ensure smooth and efficient rendering. I also faced the task of implementing responsive design to make the visualization accessible and user-friendly across various devices and screen sizes. \nAdditionally, I had to overcome the complexity of handling user interactions and providing intuitive controls for users to interact with the visualized algorithms effectively. These challenges pushed me to delve deeper into algorithm optimization, responsive web design, and user experience considerations, showcasing my ability to tackle complex technical problems in a real-world project setting. \n\n This project was inspired by ...`,
    briefDescription:
      'Interactive tool illustrating sorting algorithms visually, aiding the understanding of algorithmic processes',
    techStackList: ['React', 'Javascript', 'Typescript'],
    tagList: ['Frontend', 'Data'],
    githubLink: 'https://github.com/ollehmichael/ollehmichael.github.io',
    status: 'Completed',
  },
  {
    title: 'VIP Mobile App for Luxury Fashion Brand',
    projectID: 'luxury-fashion-mobile-app',
    imageList: [MobileApp],
    ndaSigned: true,
    description: 'Brief Description about the project concept',
    briefDescription:
      'A mobile app for VIP customers of a luxury brand, offering exclusive services',
    techStackList: ['Flutter', 'Salesforce', 'Azure DevOps'],
    tagList: ['Data'],
    githubLink: 'https://github.com/ollehmichael/ollehmichael.github.io',
    status: 'In Progress',
  },
  {
    title: 'Data Transformation for Global Beverage Company',
    projectID: 'beverage-data-transformation',
    imageList: [DataTransformation],
    ndaSigned: true,
    description: 'Brief Description about the project concept',
    briefDescription:
      'An automated data pipeline, providing real-time business insights for client-handling managers',
    techStackList: ['Python', 'Azure DevOps'],
    tagList: ['Data'],
    githubLink: 'https://github.com/ollehmichael/ollehmichael.github.io',
    status: 'In Progress',
  },
  // {
  //   title: 'Mark Six Lottery Prediction Algorithm',
  //   projectID: '',
  //   imageList: [LotteryAlgorithm],
  //   ndaSigned: false,
  //   description: 'Brief Description about the project concept',
  //   briefDescription: '',
  //   techStackList: ['Python'],
  //   tagList: ['Data'],
  //   githubLink: 'https://github.com/ollehmichael/ollehmichael.github.io',
  //   status: 'In Progress',
  // },
  // {
  //   title: 'Basketball Foul Detection System',
  //   projectID: '',
  //   imageList: [BasketballFoul],
  //   ndaSigned: false,
  //   description: 'Brief Description about the project concept',
  //   briefDescription: '',
  //   techStackList: ['Flutter', 'Salesforce'],
  //   tagList: ['Data'],
  //   githubLink: 'https://github.com/ollehmichael/ollehmichael.github.io',
  //   status: 'In Progress',
  // },
  // {
  //   title: 'Cloud hosted VPN Service',
  //   projectID: '',
  //   imageList: [CloudVPN],
  //   ndaSigned: false,
  //   description: 'Brief Description about the project concept',
  //   briefDescription: '',
  //   techStackList: ['Flutter', 'Salesforce'],
  //   tagList: ['Data'],
  //   githubLink: 'https://github.com/ollehmichael/ollehmichael.github.io',
  //   status: 'In Progress',
  // },
];
