import { Project } from '.';
import { DOMAINS, TECHNOLOGIES } from '../constants';

export const PersonalProjects: Project[] = [
  // {
  //   id: 'sorting-visualizer',
  //   title: 'Sorting Algorithm Visualizer',
  //   description:
  //     'Interactive tool illustrating sorting algorithms visually, aiding the understanding of algorithmic processes',
  //   fullDescription: [],
  //   images: [],
  //   date: '',
  //   domains: ['Frontend', 'Data'],
  //   technologies: ['React', 'Javascript', 'TypeScript'],
  //   githubUrl: '',
  //   liveUrl: '',
  //   lessons: [],
  //   achievements: [],
  //   careerExperience: 'Senior Software Engineer @Tech Innovations Inc.',
  // },
  {
    id: 'pocket-chiro',
    title: 'Pocket Chiro',
    description:
      'A mobile app connecting patients with personalized chiropractic programs, featuring AI-powered guidance and progress tracking',
    fullDescription: [],
    images: [],
    date: '',
    domains: [
      DOMAINS.MOBILE,
      DOMAINS.BACKEND,
      DOMAINS.DATA,
      DOMAINS.DEVSECOPS,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.AI_ML,
    ],
    technologies: [
      TECHNOLOGIES.REACT_NATIVE,
      TECHNOLOGIES.AI_ML,
      TECHNOLOGIES.NODE_JS,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Full Stack Developer @Pocket Chiro (Self-Employed)',
  },
  {
    id: 'influencer-marketplace',
    title: 'Influencer Marketplace Platform',
    description:
      'A platform connecting early-stage content creators with brands for authentic promotion and monetization opportunities',
    fullDescription: [],
    images: [],
    date: '',
    domains: [
      DOMAINS.WEB,
      DOMAINS.BACKEND,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.DEVSECOPS,
      DOMAINS.DATA,
    ],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.EXPRESS_JS,
      TECHNOLOGIES.TYPESCRIPT_BACKEND,
      TECHNOLOGIES.POSTGRESQL,
      TECHNOLOGIES.AZURE_CLOUD,
      TECHNOLOGIES.GITHUB_ACTIONS,
      TECHNOLOGIES.GITHUB_COPILOT,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience:
      'Full Stack Developer @Influencer Marketplace (Self-Employed)',
  },
  {
    id: 'ai-gile',
    title: 'AI-Gile Delivery Process',
    description: '',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.AI_ML],
    technologies: [
      TECHNOLOGIES.GITHUB_COPILOT,
      TECHNOLOGIES.CURSOR,
      TECHNOLOGIES.FIGMA,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Full Stack Developer @Pocket Chiro (Self-Employed)',
  },
  {
    id: 'hong-kong-developer-network',
    title: 'HK Developer Network',
    description:
      'A community platform for developers in Hong Kong to share knowledge, experiences, and elevate the tech industry reputation',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.OTHERS],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Co-Host @HK Developer Network (Co-Organized)',
  },
  {
    id: 'cover-finance',
    title: 'Cover Finance',
    description:
      'A DeFi platform exploring smart contracts, tokenomics, and decentralized financial solutions',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.BLOCKCHAIN, DOMAINS.WEB],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.SOLIDITY,
      TECHNOLOGIES.WEB3_JS,
      TECHNOLOGIES.ETHEREUM,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience:
      'Frontend Lead / Founding Member @Cover Finance (Self-Employed)',
  },
  {
    id: 'project-humankind-nft',
    title: 'Project Humankind NFT',
    description:
      'An NFT collection promoting unity and kindness across all backgrounds with the slogan "Be human, be kind"',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.BLOCKCHAIN, DOMAINS.WEB],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.SOLIDITY,
      TECHNOLOGIES.WEB3_JS,
      TECHNOLOGIES.IPFS,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience:
      'Tech Lead / Founding Member @Project Humankind NFT (Self-Employed)',
  },
  {
    id: 'comic-books',
    title: 'Fairy Tales Retold',
    description:
      'A series of comic books teaching fundamental programming concepts to children ages 5-12 through reimagined fairy tales',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.OTHERS],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Author (Almost) @Fairy Tales Retold (Self-Employed)',
  },
  {
    id: 'portfolio-website-v2',
    title: 'My Own Portfolio Website - Version 2.0',
    description:
      'A personal portfolio website showcasing who I am as a person, and as a software engineer',
    fullDescription: [''],
    images: [],
    date: '',
    domains: [DOMAINS.WEB],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.NEXT_JS,
    ],
    githubUrl: '',
    liveUrl: 'https://ollehmichael.github.io',
    lessons: [],
    achievements: [
      'Designed and developed entirely by AI, using Gen-e2 Delivery Model',
      'Finished refactoring from v1.0 to v2.0 in 20 hours',
    ],
    careerExperience: 'My Project',
  },
  {
    id: 'portfolio-website-v1',
    title: 'My Own Portfolio Website - Version 1.0',
    description:
      'A personal portfolio website showcasing who I am as a person, and as a software engineer',
    fullDescription: [''],
    images: [],
    date: '',
    domains: [DOMAINS.WEB],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.NEXT_JS,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: ['Developed the whole website in 2 full days'],
    careerExperience: 'My Project',
  },
];
