import AircraftComponentManagementHome from '@/public/projects/aircraft-component-management-home.png';
import DigitalSignageCMS from '@/public/projects/digital-signage-cms.png';
import DigitalSignageExitboardMultiple from '@/public/projects/digital-signage-exitboard-multiple.png';
import DigitalSignageExitboardSingle from '@/public/projects/digital-signage-exitboard-single.png';
import DigitalSignageNavappDetails from '@/public/projects/digital-signage-navapp-details.png';
import DigitalSignageNavapp from '@/public/projects/digital-signage-navapp.png';
import DigitalSignageStreetmap from '@/public/projects/digital-signage-streetmap.png';
import ImpactTrackerSlide from '@/public/projects/impact-tracker-slide.png';
import RenewableEnergyTradingDashboard from '@/public/projects/renewable-energy-trading-dashboard.png';
import RenewableEnergyTradingInventory from '@/public/projects/renewable-energy-trading-inventory.png';
import RenewableEnergyTradingNewDevice from '@/public/projects/renewable-energy-trading-new-device.png';
import RenewableEnergyTradingWeChatDashboard from '@/public/projects/renewable-energy-trading-wechat-dashboard.png';
import RenewableEnergyTradingWeChatLogin from '@/public/projects/renewable-energy-trading-wechat-login.png';
import RenewableEnergyTradingWeChatTradeDetails from '@/public/projects/renewable-energy-trading-wechat-trade-details.png';
import VipLoyaltySlide1 from '@/public/projects/vip-loyalty-slide-1.png';
import VipLoyaltySlide2 from '@/public/projects/vip-loyalty-slide-2.png';
import VipLoyaltySlide3 from '@/public/projects/vip-loyalty-slide-3.png';
import VipLoyaltySlide4 from '@/public/projects/vip-loyalty-slide-4.png';
import VipLoyaltySlide5 from '@/public/projects/vip-loyalty-slide-5.png';
import VipLoyaltySlide6 from '@/public/projects/vip-loyalty-slide-6.png';
import { Project } from '.';
import { DOMAINS, TECHNOLOGIES } from '../constants';

export const WorkProjects: Project[] = [
  {
    id: 'digital-signage',
    title: 'Travel Information Digital Signage Ecosystem',
    description: '',
    fullDescription: [
      'This was an extremely exciting opportunity to work with a major public transport operator to revolutionize how travelers access information on-the-go.',
      'I single-handedly developed and deployed a comprehensive digital signage ecosystem, including street-level wayfinding maps, multiple exit boards for train stations, a webapp to search for points of interest, and a backend as well as a CMS for easy data management for the internal staff.',
    ],
    lessons: [
      '# {Takeaway #1:|text-xl font-semibold} 💻 Vibe Coding Works!',
      'This was a great project for me to test out my latest setup with Gen-e2 and AI-enhanced development process, and it worked amazing.',
      'It was not perfect - there were still some fine-tuning I had to do with the instructions, prompts, workflows, and the way I was providing the context to Copilot.',
      'But overall, it was one of those projects where the requirements and scope were constantly changing on a daily basis and I was extremely anxious day and night if I would be able to deliver all the requirements on time.',
      'Despite my worries, I ended up overdelivering by {250% of the original scope|font-semibold text-success} within the same timeline, while maintaining high quality and stability.',
      "I am super proud of this achievement and it's given me more proof and confidence that I'm going in the right direction with my AI-powered development process and [Gen-e2 methodology](https://www.palo-it.com/en/services/gen-e2).",
      '# {Takeaway #2:|text-xl font-semibold} 📆 Project Management is more important than you think ',
      'This project had a lot of moving parts and tight deadlines, so I had to be very organized and efficient with my time.',
      'Especially with requirements and scope changing so often, I learned the hard way that simply {being efficient and productive|font-semibold text-success} cannot {out-produce a well-managed project|font-semibold text-destructive}.',
      'Even after all these years of developing software, {managing a project|font-semibold text-success} while {developing and managing a project alone|font-semibold text-success} proves to be an extremely challenging task.',
    ],
    achievements: [
      '✅ Single-handedly developed, deployed, and maintained this system from start to finish, including {3 frontend services|font-semibold text-success}, {1 backend service|font-semibold text-success}, {1 CMS|font-semibold text-success}, and {Azure cloud deployment|font-semibold text-success}',
      '✅ Delivered {250% more scope|font-semibold text-success} than originally planned within the same timeline',
      '✅ Reduced {HKD7000+ monthly cost|font-semibold text-success} along with eliminating {60% of data inconsistencies|font-semibold text-success} across multiple services',
    ],
    images: [
      DigitalSignageStreetmap,
      DigitalSignageExitboardSingle,
      DigitalSignageExitboardMultiple,
      DigitalSignageCMS,
      DigitalSignageNavapp,
      DigitalSignageNavappDetails,
    ],
    date: 'Oct 2025',
    domains: [
      DOMAINS.WEB,
      DOMAINS.BACKEND,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.DEVSECOPS,
      DOMAINS.AI_POWERED,
      DOMAINS.DATA,
    ],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.TYPESCRIPT_BACKEND,
      TECHNOLOGIES.NEXT_JS,
      TECHNOLOGIES.NEST_JS,
      TECHNOLOGIES.STRAPI,
      TECHNOLOGIES.PLAYWRIGHT_WEB,
      TECHNOLOGIES.NODE_JS,
      TECHNOLOGIES.JEST_WEB,
      TECHNOLOGIES.DOCKER,
      TECHNOLOGIES.AZURE_CLOUD,
      TECHNOLOGIES.AZURE_DEVOPS,
      TECHNOLOGIES.GITHUB_COPILOT,
      TECHNOLOGIES.GEN_E2_METHODOLOGY,
      TECHNOLOGIES.GOOGLE_ANALYTICS,
      TECHNOLOGIES.GOOGLE_TAG_MANAGER,
    ],
    githubUrl: '',
    liveUrl: '',
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'supply-chain-management',
    title: 'Supply Chain Management Mobile App',
    description:
      'Revamped mobile app for a luxury travel retail brand, empowering users to track inbound/outbound shipments and streamline labelling with enhanced operational efficiency',
    fullDescription: [
      'This was an interesting opportunity to test the impact I can have on a team that is facing tight deadlines and high expectations from stakeholders.',
      'There were {2 weeks left until the deadline of the project|font-semibold text-destructive}, and due to the frequent changes in the requirements and delays in management decisions, the team was {significantly behind schedule|font-semibold text-destructive}. I was brought in to help the team catch up and deliver the project on time.',
      'I had been working on [Gen-e2 methodology](https://www.palo-it.com/en/services/gen-e2) and AI-powered development process for a while, so I discussed with the team to see if this would be a good chance to leverage the powers of AI tools to accelerate our development speed without compromising the quality.',
      'With the team on board, I led the development using mainly GitHub Copilot to assist with feature development, testing, pull request reviews, and documentation. We were able to {significantly speed up our development process by 100%|font-semibold text-success} while actually {eliminating tech debts|font-semibold text-success} as well.',
    ],
    lessons: [
      '# {Takeaway #1:|text-xl font-semibold} 🐢 Slow is smooth, smooth is fast!',
      'Sometimes when we are under pressure to deliver quickly, we tend to rush through the development process and end up making mistakes or introducing bugs.',
      'This project taught me the importance of taking a step back, slowing down, and focusing on writing clean, maintainable code.',
      'By doing so, we were able to {keep ourselves aligned with the priorities and requirements|font-semibold text-success} to ultimately {spend the least amount of time|font-semibold text-success} to deliver the requirements exactly.',
      '# {Takeaway #2:|text-xl font-semibold} 🤖 AI tools are starting to mature nicely!',
      'This project was one of the first few projects where I was able to fully leverage AI tools like GitHub Copilot to assist with development.',
      'One of the most impactful uses of Copilot was during code reviews - it was able to catch potential bugs and suggest improvements that I would have otherwise missed.',
      'I already had a few sets of instructions and prompts specifically catered to catching bad practices and code smells, and having the teammates use these before they make their pull requests improved the overall code quality of the pull requests significantly.',
      'Ultimately, we were able to reduce our pull request turnover time from an average of 1 day down to 1 hour.',
      'This might sound a bit too good to be true - I know, I was {THE skeptic|font-semibold text-destructive} at our office as well when I first started experimenting with AI tools.',
      'If you are interested, feel free to reach me out and I would be happy to share more about my experiments and learnings!',
    ],
    achievements: [
      '✅ Increased delivery velocity by 2x while refactoring existing code with best practices',
      '✅ Reduced pull request turnaround by 50%',
    ],
    images: [],
    date: 'May 2025',
    domains: [
      DOMAINS.MOBILE,
      DOMAINS.BACKEND,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.DEVSECOPS,
      DOMAINS.AI_POWERED,
    ],
    technologies: [
      TECHNOLOGIES.REACT_NATIVE,
      TECHNOLOGIES.REDUX_MOBILE,
      TECHNOLOGIES.JEST_MOBILE,
      TECHNOLOGIES.GITHUB_COPILOT,
      TECHNOLOGIES.EXPRESS_JS,
      TECHNOLOGIES.TYPESCRIPT_MOBILE,
      TECHNOLOGIES.TYPESCRIPT_BACKEND,
      TECHNOLOGIES.MYSQL,
      TECHNOLOGIES.DOCKER,
      TECHNOLOGIES.ALIBABA_ACK,
      TECHNOLOGIES.GITHUB_ACTIONS,
      TECHNOLOGIES.GEN_E2_METHODOLOGY,
    ],
    githubUrl: '',
    liveUrl: '',
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'renewable-energy-trading',
    title: 'Renewable Energy Trading Platform',
    description:
      'Developed platform and admin panel for a global environmental trading firm to provide credit traders an efficient end-to-end process from onboarding clients to performing sales activities',
    fullDescription: [
      "Five separate services. Five different workflows. One frustrated trading team. For a global environmental trading firm, we consolidated the chaos into a unified platform that actually made sense. Credit traders got an end-to-end system—from onboarding new clients to closing sales—all in one place. But we didn't stop there. A WeChat Mini Program opened a new channel, giving 70%+ of customers instant access to their account highlights without the full platform complexity. Built on a monorepo with Atomic Design and secured with Microsoft Entra ID SSO, the platform balanced power with accessibility.",
    ],
    images: [
      RenewableEnergyTradingDashboard,
      RenewableEnergyTradingNewDevice,
      RenewableEnergyTradingInventory,
      RenewableEnergyTradingWeChatLogin,
      RenewableEnergyTradingWeChatDashboard,
      RenewableEnergyTradingWeChatTradeDetails,
    ],
    date: 'Mar 2025',
    domains: [
      DOMAINS.WEB,
      DOMAINS.BACKEND,
      DOMAINS.WECHAT,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.DEVSECOPS,
      DOMAINS.AI_POWERED,
    ],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.TYPESCRIPT_BACKEND,
      TECHNOLOGIES.MATERIAL_UI,
      TECHNOLOGIES.SWR,
      TECHNOLOGIES.NODE_JS,
      TECHNOLOGIES.STRAPI,
      TECHNOLOGIES.POSTGRESQL,
      TECHNOLOGIES.JEST_WEB,
      TECHNOLOGIES.GITHUB_ACTIONS,
      TECHNOLOGIES.CURSOR,
      TECHNOLOGIES.GITHUB_COPILOT,
      TECHNOLOGIES.AZURE_CLOUD,
      TECHNOLOGIES.AZURE_DEVOPS,
      TECHNOLOGIES.GOOGLE_ANALYTICS,
      TECHNOLOGIES.GOOGLE_TAG_MANAGER,
      TECHNOLOGIES.DOCKER,
      TECHNOLOGIES.GEN_E2_METHODOLOGY,
      TECHNOLOGIES.TARO_JS,
      TECHNOLOGIES.WEIXIN_DEVTOOLS,
      TECHNOLOGIES.WEIXIN_DEVELOPER_PORTAL,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [
      'Consolidated 5 separate services into a single platform to simplify operations',
      'Provided 70%+ of customers easier access through WeChat Mini Program',
    ],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'vip-loyalty',
    title: 'VIP Loyalty Mobile App',
    description:
      'A loyalty mobile app for the VIPs of a major luxury fashion & beauty brand, launched in 2 major regional markets achieving over 7000+ monthly users across iOS and Android',
    fullDescription: [
      'Luxury customers expect perfection, and this VIP loyalty app had to deliver. Launched across 2 major regional markets on both Apple Store and Google Play Store, we improved the average monthly user count from 500+ to over 7000+, all seeking personalized rewards and exclusive experiences. Leading QA testing meant obsessing over every interaction on iOS and Android—no compromises, especially for a client operating at this large of a scale. Multiple dashboards tracked user activity and system health in real-time, catching issues before customers did. From pre-launch planning to post-release firefighting, the entire journey was a collaboration with Scrum Masters and Product Owners, ensuring every feature aligned with what truly mattered.',
    ],
    images: [
      VipLoyaltySlide1,
      VipLoyaltySlide2,
      VipLoyaltySlide3,
      VipLoyaltySlide4,
      VipLoyaltySlide5,
      VipLoyaltySlide6,
    ],
    date: '',
    domains: [DOMAINS.MOBILE, DOMAINS.CLOUD_INFRA, DOMAINS.DEVSECOPS],
    technologies: [
      TECHNOLOGIES.FLUTTER,
      TECHNOLOGIES.DART,
      TECHNOLOGIES.BLOC,
      TECHNOLOGIES.GETX,
      TECHNOLOGIES.SALESFORCE_MARKETING_CLOUD,
      TECHNOLOGIES.AZURE_DEVOPS,
      TECHNOLOGIES.AZURE_CLOUD,
      TECHNOLOGIES.DATADOG,
      TECHNOLOGIES.DYNATRACE,
      TECHNOLOGIES.POSTMAN,
      TECHNOLOGIES.GIGYA,
      TECHNOLOGIES.KAKAO_AUTH,
      TECHNOLOGIES.APPLE_AUTH,
      TECHNOLOGIES.APPIUM,
      TECHNOLOGIES.AGILE_METHODOLOGY,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [
      'Launched in 2 major regional markets (KR, HKMO) for both Apple Store and Google Play Store',
      'Achieved over 7000+ monthly users',
    ],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'impact-tracker',
    title: 'Impact Tracker',
    description:
      'Led frontend development and deployed the prototype of an all-in-one platform to accelerate the delivery of ESG orchestration, monitoring & reporting',
    fullDescription: [
      "Sustainability isn't just a buzzword—it's measurable, and organizations needed the tools to prove it. As a PALO IT's first product, we built an open-source ESG data platform from the ground up. Leading frontend development meant crafting interfaces that made complex environmental, social, and governance metrics actually understandable. The prototype went live on AWS infrastructure, powered by React.js, TypeScript, and Material UI, with Redux managing state and React-i18n enabling global reach. What started as an experiment became a toolkit for organizations committed to sustainable business practices.",
    ],
    images: [ImpactTrackerSlide],
    date: '',
    domains: [
      DOMAINS.WEB,
      DOMAINS.DATA,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.DEVSECOPS,
      DOMAINS.SUSTAINABILITY,
    ],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.MATERIAL_UI,
      TECHNOLOGIES.REDUX_WEB,
      TECHNOLOGIES.AWS_CLOUD,
      TECHNOLOGIES.AZURE_DEVOPS,
      TECHNOLOGIES.GITHUB_ACTIONS,
      TECHNOLOGIES.JIRA,
      TECHNOLOGIES.AGILE_METHODOLOGY,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [
      'Led frontend development for open-source ESG data platform',
      'Successfully deployed prototype to production',
      'Designed platform to assist organizations in measuring and managing ESG performance',
    ],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'data-visualization-dashboard',
    title: 'Data Pipeline and Visualization',
    description:
      'Designed and deployed an automated ETL pipeline for a major global wine & spirits group, providing real-time business insights for sales managers',
    fullDescription: [
      'Sales managers at a leading global wine and spirits brand were drowning in data but starving for insights. We built an automated ETL pipeline that transformed chaos into clarity. Real-time business intelligence became accessible at their fingertips, cutting processing time dramatically. The pipeline pulled data from Snowflake, Azure Data Lake, and Magento, then visualized it through Microsoft PowerBI dashboards that actually made sense. Behind the scenes, Azure Functions orchestrated the entire flow, and Agile under Scrum Principles kept the team moving fast.',
    ],
    images: [],
    date: '',
    domains: [
      DOMAINS.DATA,
      DOMAINS.BACKEND,
      DOMAINS.CLOUD_INFRA,
      DOMAINS.DEVSECOPS,
    ],
    technologies: [
      TECHNOLOGIES.PYTHON,
      TECHNOLOGIES.SNOWFLAKE,
      TECHNOLOGIES.MAGENTO,
      TECHNOLOGIES.AZURE_CLOUD,
      TECHNOLOGIES.POWER_BI,
      TECHNOLOGIES.AGILE_METHODOLOGY,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [
      'Achieved >60% reduction in data processing time',
      'Enabled near real-time business insights for sales managers',
      'Automated ETL pipeline for leading global wine & spirits brand',
    ],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'aircraft-component-management',
    title: 'Aircraft Component Management System',
    description:
      'Led frontend development of an award-winning platform for a specialized high-tech electronic component manufacturer, improving operational efficiency for international industrial operations',
    fullDescription: [
      "An international industrial company needed precision—tracking aircraft components isn't something you can afford to get wrong. Leading the frontend development for this award-winning platform meant building interfaces that made complex component management feel effortless. Every maintenance schedule, every compliance requirement, every part in the supply chain needed to be tracked with absolute accuracy. Built with React.js, TypeScript, and Material UI, powered by Redux for state management, the platform transformed operational efficiency for a specialized high-tech electronic component manufacturer. Agile under Scrum Principles kept the development sharp and responsive.",
    ],
    images: [AircraftComponentManagementHome],
    date: '',
    domains: [
      DOMAINS.WEB,
      DOMAINS.BACKEND,
      DOMAINS.DATA,
      DOMAINS.DEVSECOPS,
      DOMAINS.SUSTAINABILITY,
      DOMAINS.BLOCKCHAIN,
    ],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.MATERIAL_UI,
      TECHNOLOGIES.REDUX_WEB,
      TECHNOLOGIES.AGILE_METHODOLOGY,
      TECHNOLOGIES.HYPERLEDGER_FABRIC,
      TECHNOLOGIES.AWS_CLOUD,
      TECHNOLOGIES.IPFS,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [
      'Led frontend development of award-winning platform',
      'Improved operational efficiency for international industrial company',
      'Built comprehensive tracking system for aircraft components and compliance',
    ],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'gen-e2-methodology',
    title: 'Gen-e2 Methodology Framework',
    description:
      'An innovative agile methodology framework combining entrepreneurial mindset with engineering excellence',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.AI_POWERED],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'lnl-wechat-miniprogram',
    title: 'Lunch & Learn - WeChat Mini Program',
    description:
      'A feature-rich WeChat mini program delivering seamless mobile experiences within the WeChat ecosystem',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.WECHAT, DOMAINS.TALKS_WORKSHOPS],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'lnl-gen-e2-methodology',
    title: 'Lunch & Learn - Gen-e2 Methodology Implementation',
    description:
      'Implementation of Gen-e2 methodology for learning and development initiatives',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.AI_POWERED, DOMAINS.TALKS_WORKSHOPS],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'lnl-ai-powered-delivery',
    title:
      'Lunch & Learn - How to design, develop, and deploy a product only with AI',
    description:
      'My experiments on going through the entire PDLC using AI tools only',
    fullDescription: [],
    images: [],
    date: 'Mar 2024',
    domains: [DOMAINS.OTHERS],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'bcorp-certification',
    title: 'B Corp Certification Initiative',
    description:
      'Leading the technical aspects of B Corporation certification, ensuring sustainable and ethical business practices',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.SUSTAINABILITY],
    technologies: [],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Software Engineer @PALO IT Hong Kong Limited',
  },
  {
    id: 'ecommerce-platform',
    title: 'Ecomportal',
    description:
      'Revamped a job board for the eCommerce industry, resolving 85% of all identified bugs and enhancing performance by leveraging server-side rendering components',
    fullDescription: [
      'The eCommerce industry moves fast, and job seekers needed a platform that could keep up. Ecomportal was struggling with bugs and performance issues that frustrated users daily. We tore through the codebase, resolving 85% of all identified bugs while completely overhauling the user experience. Server-side rendering components transformed load times, making the platform feel instant. Built with Next.js, TypeScript, and Radix UI, backed by MongoDB and Algolia Search Engine for lightning-fast job searches. Stripe handled payments seamlessly, while Google Search Console optimized discoverability. What emerged was a job board that finally matched the speed of the industry it served.',
    ],
    images: [],
    date: '',
    domains: [DOMAINS.WEB, DOMAINS.BACKEND],
    technologies: [
      TECHNOLOGIES.NEXT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.RADIX_UI,
      TECHNOLOGIES.MONGODB,
      TECHNOLOGIES.SANITY,
      TECHNOLOGIES.STRIPE,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [
      'Resolved 85% of all identified bugs',
      'Enhanced performance through server-side rendering components',
      'Revamped complete job board for eCommerce industry',
    ],
    careerExperience: 'Full Stack Developer @Ecomportal (Self-Employed)',
  },
  {
    id: 'sketch-basketball-website',
    title: 'Sketch Basketball Website',
    description:
      'A website and admin panel for managing basketball league operations, schedules, and player information',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.WEB, DOMAINS.BACKEND],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.NODE_JS,
      TECHNOLOGIES.MATERIAL_UI,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.TYPESCRIPT_BACKEND,
      TECHNOLOGIES.PYTHON,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Frontend Lead @Sketch Basketball Limited',
  },
  {
    id: 'emsd-energy-management',
    title: 'EMSD Energy Management System',
    description:
      'An energy management system for monitoring and optimizing building energy consumption and efficiency',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.DATA, DOMAINS.WEB, DOMAINS.BACKEND],
    technologies: [TECHNOLOGIES.REACT_JS, TECHNOLOGIES.NODE_JS],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Junior Software Developer @Dayta AI Limited',
  },
  {
    id: 'cyclops-dashboard',
    title: 'Cyclops Dashboard',
    description:
      'An advanced monitoring and analytics dashboard providing real-time insights and system health metrics',
    fullDescription: [],
    images: [],
    date: '',
    domains: [DOMAINS.WEB, DOMAINS.DATA],
    technologies: [
      TECHNOLOGIES.REACT_JS,
      TECHNOLOGIES.TYPESCRIPT_WEB,
      TECHNOLOGIES.GOLANG_BACKEND,
    ],
    githubUrl: '',
    liveUrl: '',
    lessons: [],
    achievements: [],
    careerExperience: 'Junior Software Developer @Dayta AI Limited',
  },
];
